### ISSUE TITLE
Can not download the data

### ISSUE THREAD

**Issue by SHIELD-SKY** [NrgXnat/oasis-scripts#1]
when i use `download_oasis_scans_wget.sh` to  download OASIS-3 data, 
There is some errors:
```
Downloading all scans for OAS30001_MR_d0129.
--2018-06-13 10:36:22--  https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0129/scans/ALL/files?format=tar.gz
Resolving central.xnat.org (central.xnat.org)... 128.252.155.45
Connecting to central.xnat.org (central.xnat.org)|128.252.155.45|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gtar]
Saving to: ‘data/OAS30001_MR_d0129.tar.gz’

data/OAS30001_MR_d0129.tar.gz                 [                     <=>                                                            ]   2.42M  8.82KB/s    in 4m 41s  

2018-06-13 10:41:51 (8.82 KB/s) - ‘data/OAS30001_MR_d0129.tar.gz’ saved [2540574]

Could not download all scans for OAS30001_MR_d0129.
```

Due to this error,  download code will delete the invalid data. Hence nothing will be keep.

Can you give me a favor? please.

**Comment by SHIELD-SKY** [comment]
another two shell code also have same problems. Nothing be keep in my ubuntu

**Comment by sarahkeefe** [comment]
Hi, The script will delete data if the downloaded compressed file is invalid. This is likely a connection issue with XNAT Central that I haven't been able to figure out yet. I'll update if I find out anything.

**Comment by SHIELD-SKY** [comment]
ok , thanks.

**Comment by sarahkeefe** [comment]
Hello, we've recently updated our network and it has improved similar download issues for many users. Please retry and let me know if you continue to experience this same issue. If you find a different problem feel free to open a new issue.

**Comment by 4tur** [comment]
I'm having this issue, it all seems to connect well but it doesn't download any data.:


Downloading all scans for OAS30001_MR_d0129.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    529      0 --:--:-- --:--:-- --:--:--   529
Could not download all scans for OAS30001_MR_d0129.
Done with OAS30001_MR_d0129.
Downloading all scans for OAS30001_MR_d0757.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    482      0 --:--:-- --:--:-- --:--:--   482
Could not download all scans for OAS30001_MR_d0757.
Done with OAS30001_MR_d0757.
Downloading all scans for OAS30001_MR_d2430.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    499      0 --:--:-- --:--:-- --:--:--   498
Could not download all scans for OAS30001_MR_d2430.
Done with OAS30001_MR_d2430.
HTTP/1.1 200 OK
