### ISSUE TITLE
download freesurfer error

### ISSUE THREAD

**Issue by bieqa** [NrgXnat/oasis-scripts#13]
The script is correct. However, we were only able to download a few of datasets. It seems that the rest of freesurfer processed data cannot be downloaded.

Thanks!

**Comment by sarahkeefe** [comment]
Hi, are you still having this issue? If you could provide details on the error or output you're getting I can help you troubleshoot. There may have also been temporary downtime of the server so re-trying could help as well.

**Comment by sarahkeefe** [comment]
I'm going to close this issue, but feel free to re-open it with more specific details and error messages if you are still experiencing a similar issue.

**Comment by kunal-kadam** [comment]
Enter your password for accessing OASIS data on XNAT Central:
.associated with OAS30001_AV45_d2430PTIMECOURSE_d2430
curl: (3) Illegal characters found in URL
.in OAS30001_AV45_d2430OAS30001_AV45_PUPTIMECOURSE_d2430
.one with OAS30001_AV45_PUPTIMECOURSE_d2430
.associated with OAS30001_PIB_d0423PTIMECOURSE_d0423
curl: (3) Illegal characters found in URL
.in OAS30001_PIB_d0423 OAS30001_PIB_PUPTIMECOURSE_d0423
.one with OAS30001_PIB_PUPTIMECOURSE_d0423
.associated with OAS30001_PIB_d0847PTIMECOURSE_d0847
curl: (3) Illegal characters found in URL
.in OAS30001_PIB_d0847 OAS30001_PIB_PUPTIMECOURSE_d0847
.one with OAS30001_PIB_PUPTIMECOURSE_d0847
.associated with OAS30001_PIB_d1317PTIMECOURSE_d1317
curl: (3) Illegal characters found in URL
.in OAS30001_PIB_d1317 OAS30001_PIB_PUPTIMECOURSE_d1317
.one with OAS30001_PIB_PUPTIMECOURSE_d1317
.associated with OAS30001_PIB_d2438PTIMECOURSE_d2438
curl: (3) Illegal characters found in URL
.in OAS30001_PIB_d2438 OAS30001_PIB_PUPTIMECOURSE_d2438
.one with OAS30001_PIB_PUPTIMECOURSE_d2438
.associated with OAS30001_PIB_d3132PTIMECOURSE_d3132
curl: (3) Illegal characters found in URL
.in OAS30001_PIB_d3132 OAS30001_PIB_PUPTIMECOURSE_d3132
.one with OAS30001_PIB_PUPTIMECOURSE_d3132
.associated with OAS30002_AV45_d2340PTIMECOURSE_d2340
curl: (3) Illegal characters found in URL
.in OAS30002_AV45_d2340OAS30002_AV45_PUPTIMECOURSE_d2340
.one with OAS30002_AV45_PUPTIMECOURSE_d2340
.associated with OAS30002_PIB_d0975PTIMECOURSE_d0975
curl: (3) Illegal characters found in URL
.in OAS30002_PIB_d0975 OAS30002_PIB_PUPTIMECOURSE_d0975
.one with OAS30002_PIB_PUPTIMECOURSE_d0975
.associated with OAS30002_PIB_d2345PTIMECOURSE_d2345
curl: (3) Illegal characters found in URL
.in OAS30002_PIB_d2345 OAS30002_PIB_PUPTIMECOURSE_d2345
.one with OAS30002_PIB_PUPTIMECOURSE_d2345
.associated with OAS30003_AV45_d2682PTIMECOURSE_d2682
curl: (3) Illegal characters found in URL
.in OAS30003_AV45_d2682OAS30003_AV45_PUPTIMECOURSE_d2682
.one with OAS30003_AV45_PUPTIMECOURSE_d2682
HTTP/1.1 200 OK
Set-Cookie: SESSION_EXPIRATION_TIME="1642276534797,900000"; Version=1; Path=/
Date: Sat, 15 Jan 2022 19:55:34 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0


Receving this as error
