### ISSUE TITLE
curl: (18) transfer closed with outstanding read data remaining                                                                            

### ISSUE THREAD

**Issue by mengweiren** [NrgXnat/oasis-scripts#16]
I am trying to download the OASIS3 data with the provided script and ran the command as follow, but I got the CURL error as in title after downloading only a small number of data (e.g., 4 subjects). 
`./download_oasis_scans_bids.sh ../../subjects.csv  ../../oasis_bids/  myusername T1w,T2w`

I tried to look into the detailed instruction for downloading as BIDS format but the link in README is invalid. 
Could you please provide some hint on this? Thanks!

Regards,

**Comment by sarahkeefe** [comment]
I fixed the link in the README - thanks for pointing that out.

A couple things:

There was a server outage yesterday that may have affected your download. It's fixed now, so you may want to re-try today and see if you still get the error.

If it still doesn't work - what version of curl is on your machine? You can check with `curl -V`. I found an issue posted about this sometimes happening with an older version of curl. If your curl version is older (the oldest version I've used is 7.29.0 and which seems to work fine) you could update your curl version.

If neither of those work, I'll investigate what might need updating.

**Comment by mengweiren** [comment]
Thank you for the prompt reply! I retried and it worked, so I guess it's the server problem. My curl is 7.29.0 too. 

Thanks again,
