### ISSUE TITLE
Download issue  (download_oasis_scans.sh) - no such file or directory

### ISSUE THREAD

**Issue by radvilemaur** [NrgXnat/oasis-scripts#19]
I am having the same issue when running the download_oasis_scans.sh as https://github.com/NrgXnat/oasis-scripts/issues/18. My  files seem to be in correct format.  Attached the csv file. 
[matched_baseline_mr_within_365_days.csv](https://github.com/NrgXnat/oasis-scripts/files/7710480/matched_baseline_mr_within_365_days.csv)

Snippet of the error: 

.ownloading all scans for OAS31164_MR_d0069
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS31164_MR_d0069
rm: cannot remove 'rm5417/OAS31164_MR_d0069'$'\r''.zip': No such file or directory
.one with OAS31164_MR_d0069
.ownloading all scans for OAS31167_MR_d0064
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS31167_MR_d0064
rm: cannot remove 'rm5417/OAS31167_MR_d0064'$'\r''.zip': No such file or directory
.one with OAS31167_MR_d0064
.ownloading all scans for OAS31168_MR_d0148
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS31168_MR_d0148
rm: cannot remove 'rm5417/OAS31168_MR_d0148'$'\r''.zip': No such file or directory
.one with OAS31168_MR_d0148
HTTP/1.1 200 OK
Set-Cookie: JSESSIONID=central.xnat.org2~8AF0CB44FB7C1BA94C3FB3D16D699B50; Path=/; HttpOnly
Set-Cookie: SESSION_EXPIRATION_TIME="1639474776243,900000"; Version=1; Path=/
Date: Tue, 14 Dec 2021 09:39:36 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0

**Comment by sarahkeefe** [comment]
Hi, the dots at the beginning of some of the lines plus the error line containing '\r' are indicating to me that your csv file is most likely not in Unix format. Follow the instructions in this section to convert your file to Unix format and retry the script: [https://github.com/NrgXnat/oasis-scripts#note-on-unix-file-formatting](https://github.com/NrgXnat/oasis-scripts#note-on-unix-file-formatting)

I recommend installing the dos2unix program for this as it is the most foolproof.

**Comment by radvilemaur** [comment]
Dear Sarah, 

Thank you, I skipped this step accidentaly. Nonetheless, I tried the 3 different ways and still nothing is downloading. Last time I used this script it worked with saving the notepad file. 

Using dos2unix here -  there might be an issue with dos2unix?

![image](https://user-images.githubusercontent.com/57565417/146168852-2f19db8e-9d54-4683-b3cb-f8a7524d722e.png)

And here using tr :
<img width="948" alt="example" src="https://user-images.githubusercontent.com/57565417/146170045-1bb0add3-fef5-4dd2-890e-ce17b6cc7111.png">

Is there anything else I am missing here and could try doing?

**Comment by sarahkeefe** [comment]
Hi, it looks like you're missing an argument in your script command. You'll need to add a name of a directory to create and download to after the .csv filename in the script command. So like this:

`./download_oasis_scans.sh matched_baseline_mr_within_365_days.csv downloaded_scans rm5417 T1w`

I'm not able to 100% confirm whether dos2unix is working in your first example - I usually get a message that tells me it converted the file to Unix format but I didn't see that in your screenshot. So there's a small chance your dos2unix program is not working correctly but I can't be sure.

The fact that your second download attempted to download with a blank label ("Downloading all scans for .") was unusual as well. You may want to run `cat matched_baseline_mr_within_365_days.csv` to display what you have in that file and make absolutely sure it is a single column of OASIS session labels. But there is a chance that correcting the inputs to the script will solve that problem so you may not need to check that.

**Comment by radvilemaur** [comment]
Thank you, It worked with the directory -  I thought if its not provided it will be created automatically according to the information provided, but I might have been mistaken. Thank you.

**Comment by kunal-kadam** [comment]
`-bash: ./download_oasis_scans.sh: /bin/bash^M: bad interpreter: No such file or directory
`
Solution `sed -i -e 's/\r$//' download_oasis_scans.sh`

then follow the dos2unix command from doc it worked !
