### ISSUE TITLE
[: 18: unexpected operator and read: Illegal option -s

### ISSUE THREAD

**Issue by Rhuax** [NrgXnat/oasis-scripts#2]
I'm on Ubuntu 19, and I get those errors on every script. I tried to get around removing -s and removing the first if, but after inserting the password the script terminates.

**Comment by sarahkeefe** [comment]
Which script are you using, and can you post the full command you are running? 

A couple thoughts:
- Are you running the script using the correct shell? 
- You may have a firewall blocking your connection that is causing the cURL call to fail.

**Comment by Rhuax** [comment]
./download_oasis_scans.sh in.csv prova Rhuax

prova is the folder name, rhuax is my nickname

**Comment by sarahkeefe** [comment]
can you post the output you get when you type in `curl --version` ?

**Comment by Rhuax** [comment]
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL

**Comment by sarahkeefe** [comment]
It looked like your error is with the CURL call but  I don't see anything unusual there. Have you tried running ./download_oasis_scans_wget.sh instead?

**Comment by Rhuax** [comment]
I get the same error with all the scripts. I'm starting to thinking it's not your fault, my some weird thing in my pc

**Comment by sarahkeefe** [comment]
Hi, I've been in contact with another user who had the same issue and I was able to fix the problem. I just pushed the fix. Go ahead and try the updated scripts and see if they work for you. I'm going to close this issue for now, feel free to re-open it if your problem persists.
