### ISSUE TITLE
Please give the proper commands to get the data for windows machine. 

### ISSUE THREAD

**Issue by kunal-kadam** [NrgXnat/oasis-scripts#20]
I am trying to run the scripts for downloading the scan files using all the given files in scan folder but none of them is working in my case. Please give the proper instructions to get the file in the pc and if possible also give the example command.

**Comment by kunal-kadam** [comment]
![image](https://user-images.githubusercontent.com/62118171/149622540-46187196-9982-401f-931f-c06f643c6231.png)

**Comment by kunal-kadam** [comment]
Enter your password for accessing OASIS data on XNAT Central:
.ownloading all scans for OAS30001_MR_d0129
curl: (3) URL using bad/illegal format or missing URL
download_oasis_scans.sh: line 138: zip: command not found
.ould not download all scans for OAS30001_MR_d0129
rm: cannot remove './data/OAS30001_MR_d0129'$'\r''.zip': No such file or directory
.one with OAS30001_MR_d0129
.ownloading all scans for OAS30001_MR_d0757
curl: (3) URL using bad/illegal format or missing URL
download_oasis_scans.sh: line 138: zip: command not found
.ould not download all scans for OAS30001_MR_d0757
rm: cannot remove './data/OAS30001_MR_d0757'$'\r''.zip': No such file or directory
.one with OAS30001_MR_d0757
.ownloading all scans for OAS30001_MR_d2430
curl: (3) URL using bad/illegal format or missing URL
download_oasis_scans.sh: line 138: zip: command not found
.ould not download all scans for OAS30001_MR_d2430
rm: cannot remove './data/OAS30001_MR_d2430'$'\r''.zip': No such file or directory
.one with OAS30001_MR_d2430
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0HTTP/1.1 200 OK
Set-Cookie: SESSION_EXPIRATION_TIME="1642251423319,900000"; Version=1; Path=/
Date: Sat, 15 Jan 2022 12:57:03 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0

**Comment by kunal-kadam** [comment]
Enter your password for accessing OASIS data on XNAT Central:
.ownloading all scans for OAS30001_MR_d0129
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS30001_MR_d0129
rm: cannot remove './data/OAS30001_MR_d0129'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0129
.ownloading all scans for OAS30001_MR_d0757
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS30001_MR_d0757
rm: cannot remove './data/OAS30001_MR_d0757'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0757
.ownloading all scans for OAS30001_MR_d2430
curl: (3) URL using bad/illegal format or missing URL
.ould not download all scans for OAS30001_MR_d2430
rm: cannot remove './data/OAS30001_MR_d2430'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d2430
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0HTTP/1.1 200 OK
Set-Cookie: SESSION_EXPIRATION_TIME="1642251758591,900000"; Version=1; Path=/
Date: Sat, 15 Jan 2022 13:02:38 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0


for tar script

**Comment by kunal-kadam** [comment]
please give the instructions to solve this issue i had tried to debug then i found that the url is not getting properly executed

**Comment by sarahkeefe** [comment]
Hi, please see this response to issue 19: https://github.com/NrgXnat/oasis-scripts/issues/19#issuecomment-993668445

Based on your output you are having the same issue. Please follow the instructions and retry.
