### ISSUE TITLE
 How to get the diagnosis information of participants

### ISSUE THREAD

**Issue by funfanfuns** [NrgXnat/oasis-scripts#27]
I have download the MRI data from the OASIS3 dataset. However, I don't know how to get the diagnosis information of participants (i.e., Alzheimer‘s disease, mild cognitive impairment, or cognitive normal). For example, I have downloaded the freesurfer data of the participant whose freesurfer_id is OAS30001_Freesurfer53_d2430. I found this participant (OAS30001) in ADRC Clinical Data tab. However, I can't find the diagnosis information corresponding to the date of the freesurfer data (d2430) in ADRC Clinical Data tab.

**Comment by sarahkeefe** [comment]
Hi, we don't have diagnosis information taken at each scan timepoint. Instead you need to match up the scan session with its closest ClinicalData timepoint. Matching up ClinicalData entries to scan session timepoints must be done manually based on your own criteria of what is a valid length of time between a ClinicalData entry and MR, PET, or CT scan session. More details on what you need to do and the script you can use to do this can be found here: [https://github.com/NrgXnat/oasis-scripts#matching-up-session-data-by-days-from-entry](url).
