### ISSUE TITLE
problem downloading oasis4

### ISSUE THREAD

**Issue by firatozdemir** [NrgXnat/oasis-scripts#29]
Hello,

I know the readme says this repo is for downloading OASIS3 but [OASIS-4 webpage](https://www.oasis-brains.org/) also references this repo for OASIS4 downloads. I could download OASIS3 without problems, but same script returns `Could not download all scans for {label_id}` kind of error. 

I use the exact setup I used for downloading OASIS3 when trying to download OASIS4. The only difference being different csv file with label_ids that come from OASIS4 instead. For example:

```
./oasis-scripts/download_scans/download_oasis_scans.sh csv.csv . ${uname}
```

where csv.csv contains
```
OAS42699_MR_d3010
OAS42700_MR_d3015
```

**Comment by firatozdemir** [comment]
Awesome, thanks that fixes it!

**Comment by sarahkeefe** [comment]
Finally got around to fixing this - if you run into any other problems feel free to open another issue!
