### ISSUE TITLE
XNAT Central no MR ID field

### ISSUE THREAD

**Issue by iitzco** [NrgXnat/oasis-scripts#3]
Hi,

I've tried to follow the instructions included in the README file. For OASIS 3 projects [here](https://central.xnat.org/data/projects/OASIS3), there is no MR ID field when trying to edit columns.

This step blocks the CSV download and hence, the data download.

How can I fix this problem?

**Comment by sarahkeefe** [comment]
Hi, When selecting sessions to download on XNAT, the "MR ID" should be automatically selected by default (on the left column of the screen) when you select the MR Sessions tab. If you don't see the MR Sessions tab when you visit the OASIS3 project page, click on the "Add Tab" dropdown menu and select "MR Sessions". This should add the correct tab that includes the MR ID. I've highlighted that button in yellow below.

![oasis3_add_tab](https://user-images.githubusercontent.com/264991/45038875-ca5b6300-b027-11e8-8f32-1b5724feff45.png)

If you have more questions on use of XNAT (the website where OASIS is hosted), you can contact the XNAT-discussion Google group here: [https://groups.google.com/forum/#!forum/xnat_discussion](https://groups.google.com/forum/#!forum/xnat_discussion)

**Comment by iitzco** [comment]
Thanks @sarahkeefe !
The problem was the MR Sessions tab...
