### ISSUE TITLE
tar error when downloading OASIS3

### ISSUE THREAD

**Issue by clarkenj** [NrgXnat/oasis-scripts#30]
Hi, I downloaded OASIS3 data using the `download_oasis_scans_bids.sh` script. However I am having trouble untaring the data. When I run `file OAS30872_MR_d3057.tar.gz` I get `HTML document, ASCII text`. If I do try and untar, I get the following error:

```
tar: This does not look like a tar archive
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

I also tried renaming to only `.tar `extension, with a similar error. Is it a problem with `wget` perhaps?

**Comment by clarkenj** [comment]
I re-ran it without the `-b` switch given in line 7 of the script, I'm not sure if that was causing the issue or something else. But it worked.

**Comment by sarahkeefe** [comment]
Sorry for the delay! Thanks for finding the issue! Was the -b only listed in the comments in the download_oasis_scans_bids.sh script file? I removed it from line 7 - if you see it anywhere else, or if it's in any documentation, let me know and I can fix it. Thanks again!

**Comment by clarkenj** [comment]
Yes that's the only place it was listed. No problem!
