### ISSUE TITLE
OASIS Access

### ISSUE THREAD

**Issue by PaulKMandal** [NrgXnat/oasis-scripts#35]
Good afternoon,

I apologize in advance for creating an issue request here, but I have submitted multiple requests to access the OASIS 3 and 4 datasets, the first one being submitted over a month ago. I was hoping that one of the authors of this repo is an owner of the data repository hosted on Central.

I apologize for posting an issue here, but have not received a response from their email yet.

**Comment by PaulKMandal** [comment]
Closing, got it resolved.

**Comment by shoyo44** [comment]
> Closing, got it resolved.

bro how did you the access to the dataset, can you give me any insights for accessing the OASIS 3 dataset.It would be very helpful for my research paper.
