### ISSUE TITLE
Illegal characters in URL

### ISSUE THREAD

**Issue by Cojabi** [NrgXnat/oasis-scripts#36]
We are trying to download OASIS3 PIB, AV45 and FDG PET data but run into an issue we can not wrap our heads around. Any help would be highly appreciated.

**our call:**
`./download_oasis_scans.sh ~/oasis_test3.csv path/to/folder username`

**oasis_test3.csv:**
```
OAS30001_AV45_d2430
OAS30001_FDG_d2650
OAS30001_PIB_d0423
```

**Output:**

```
Enter your password for accessing OASIS data on XNAT Central:

.ownloading all scans for ﻿OAS30001_AV45_d2430
/scans/ALL/files?format=zipta/archive/projects/OASIS3/subjects/﻿OAS30001/experiments/﻿OAS30001_AV45_d2430
curl: (3) Illegal characters found in URL
.ould not download all scans for ﻿OAS30001_AV45_d2430
rm: cannot remove 'path/to/folder/﻿OAS30001_AV45_d2430'$'\r''.zip': No such file or directory
.one with ﻿OAS30001_AV45_d2430
.ownloading all scans for OAS30001_FDG_d2650
/scans/ALL/files?format=zipta/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_FDG_d2650
curl: (3) Illegal characters found in URL
.ould not download all scans for OAS30001_FDG_d2650
rm: cannot remove 'path/to/folder/OAS30001_FDG_d2650'$'\r''.zip': No such file or directory
.one with OAS30001_FDG_d2650
HTTP/1.1 200 OK
Set-Cookie: SESSION_EXPIRATION_TIME="1701877711829,900000"; Version=1; Path=/
Date: Wed, 06 Dec 2023 15:48:31 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0
```

**Comment by sarahkeefe** [comment]
Hi, this is the error that happens when your input .csv file isn’t in Unix format. Try converting your file to Unix format and rerunning. 

The script documentation includes instructions for a couple ways to do this here: [https://github.com/NrgXnat/oasis-scripts#creating-a-csv-file-for-use-with-these-scripts](https://github.com/NrgXnat/oasis-scripts#creating-a-csv-file-for-use-with-these-scripts)

**Comment by Cojabi** [comment]
Thank you for replying so quickly.

Unfortunately, it's not the formatting. We work on UNIX systems (Linux, macOS) and the csv is UTF-8 encoded.

**Comment by Cojabi** [comment]
We found the issue and it was related to the newline characters. 
Thank you!
