### ISSUE TITLE
problems downloading scans 

### ISSUE THREAD

**Issue by ZiyunLiang** [NrgXnat/oasis-scripts#38]
Hi, when I am trying to download the scans, using this command: 
`./download_oasis_scans.sh oasis_scan_download_example.csv /data2/data username`
I got the following output:
```
Enter your password for accessing OASIS data on XNAT Central:
Downloading all scans for OAS30001_MR_d0129.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0129/scans/ALL/files?format=zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    565      0 --:--:-- --:--:-- --:--:--   566
Could not download all scans for OAS30001_MR_d0129.
Done with OAS30001_MR_d0129.
Downloading all scans for OAS30001_MR_d0757.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0757/scans/ALL/files?format=zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    622      0 --:--:-- --:--:-- --:--:--   622
Could not download all scans for OAS30001_MR_d0757.
Done with OAS30001_MR_d0757.
Downloading all scans for OAS30001_MR_d2430.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d2430/scans/ALL/files?format=zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   298  100   298    0     0    652      0 --:--:-- --:--:-- --:--:--   653
Could not download all scans for OAS30001_MR_d2430.
Done with OAS30001_MR_d2430.
HTTP/1.1 200 OK
Set-Cookie: JSESSIONID=central.xnat.org3~C607A7D48CC1251EA4C1D5F584933016; Path=/; HttpOnly
Set-Cookie: SESSION_EXPIRATION_TIME="1710945193934,900000"; Version=1; Path=/
Date: Wed, 20 Mar 2024 14:33:13 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0
```
It did not download anything to my folder. Do you know what could possibly be wrong? 

I have applied and been granted access to this dataset. But today I am not able to log in to the CENTRAL system or change my password (with a lot of attempts). Don't know if the two problems are related. 

Thank you for your help!

**Comment by sarahkeefe** [comment]
Hi, yes, if you aren't able to log into XNAT Central with the same username that you're using as input to the script then the script won't work. Try again once you are able to log in and access the data in XNAT Central. I'm going to close this issue for now since it's not an issue with the script but feel free to open a new one if you run into other issues.

**Comment by ZiyunLiang** [comment]
Thanks for your quick reply! I was granted access yesterday. And last night I was able to log in to XNAT Central but today I am not able to do it with the same account no matter how I tried. Do you know if there is any problem happening with the server right now or if it's my account problem? Thank you!

**Comment by sarahkeefe** [comment]
Ooh, yep, I just tried and I can't log in either. I'll send in an error report. Sorry about that!

**Comment by ZiyunLiang** [comment]
Thank you!
