### ISSUE TITLE
Cannot download Data

### ISSUE THREAD

**Issue by ET18** [NrgXnat/oasis-scripts#4]
I tried downloading the data using the shell script you provided as well as directly from xnat website and it's not working. I would appreciate if you can give some guidance on how to proceed.

**Comment by sarahkeefe** [comment]
Can you post the command you are using to run the script and the error/result you are getting?

**Comment by ET18** [comment]
Thanks for quick response. Here it is:
./download_oasis_scans.sh filenames.csv oasis3images my_user_name

Downloading all scans for Subject,M/F,Hand,YOB,UDS A1: Sub Demos,UDS B6: GDS,UDS B8: Phys. Neuro Findings,Psych Assessments,UDS A2: Informant Demos,UDS B7: FAQs,UDS D1: Clinician Diagnosis,UDS A5: Sub Health Hist.,UDS B2: HIS and CVD,UDS A3: Partcpt Family Hist.,PETs,UDS B3: UPDRS,MR Sessions,UDS B9: Clin. Judgements,ADRC Clinical Data,UDS B5: NPI-Q.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: A1
curl: (6) Could not resolve host: Sub
curl: (6) Could not resolve host: Demos,UDS
curl: (6) Could not resolve host: B6
curl: (6) Could not resolve host: GDS,UDS
curl: (6) Could not resolve host: B8
curl: (6) Could not resolve host: Phys
curl: (6) Could not resolve host: Neuro

...
..

Could not download all scans for Subject,M/F,Hand,YOB,UDS A1: Sub Demos,UDS B6: GDS,UDS B8: Phys. Neuro Findings,Psych Assessments,UDS A2: Informant Demos,UDS B7: FAQs,UDS D1: Clinician Diagnosis,UDS A5: Sub Health Hist.,UDS B2: HIS and CVD,UDS A3: Partcpt Family Hist.,PETs,UDS B3: UPDRS,MR Sessions,UDS B9: Clin. Judgements,ADRC Clinical Data,UDS B5: NPI-Q.
rm: oasis3images/Subject,M/F,Hand,YOB,UDS: No such file or directory
rm: A1:: No such file or directory
rm: Sub: No such file or directory
rm: Demos,UDS: No such file or directory
rm: B6:: No such file or directory
rm: GDS,UDS: No such file or directory
rm: B8:: No such file or directory
rm: Phys.: No such file or directory
rm: Neuro: No such file or directory
rm: Findings,Psych: No such file or directory
rm: Assessments,UDS: No such file or directory
rm: A2:: No such file or directory
rm: Informant: No such file or directory

**Comment by ET18** [comment]
I am running this on Mac and curl works in general.

**Comment by sarahkeefe** [comment]
Hi, It looks like you haven't formatted your input CSV file (filenames.csv) correctly. The input file needs to only contain a list of the MR session IDs you want to download and nothing else. Each ID should be on a separate line. Check out the file [oasis_scan_download_example.csv](https://github.com/NrgXnat/oasis-scripts/blob/master/oasis_scan_download_example.csv) for an example of the type of file you need to use. 

You can also go to this wiki page: [https://wiki.xnat.org/display/CENTRAL/OASIS+on+XNAT+Central](https://wiki.xnat.org/display/CENTRAL/OASIS+on+XNAT+Central) for more information on how to use the XNAT interface to create a spreadsheet for use with this script.

**Comment by ET18** [comment]
Thank you for the help. I'm sorry that I hadn't looked into the example file carefully. I'll have it another go. Thank you!

**Comment by sarahkeefe** [comment]
Great, I'm going to close this issue. Feel free to open a new issue if you run into other problems!

**Comment by ET18** [comment]
Just a quick question though: Do I have to have a list of image files' names? Or is it possible to download everything per subject? I don't know how to access the image file names. Also if I download them all separately,  this would make it difficult to link with other information belonging to that subject.

**Comment by sarahkeefe** [comment]
Hi, You don't need to have the image file names to download them, just the IDs should be enough. 

Are you looking to download all scans for a subject, or all MR/PET scans, Freesurfer, and PET pipeline output for a subject? Right now I only have separate scripts available for each, and I haven't yet made one to download based on subject ID. If that's something you'd be interested in I can work on it.

To download every scan for a specific subject right now, you still need to use download_oasis_scans.sh and provide the list of all MR or PET sessions available for that subject. There are two main ways to do this: you can either download the full list of MR or PET sessions and use a spreadsheet program like Excel to filter it by Subject ID, or you can use the XNAT Central interface to filter the list to include only the subjects you want.

---

In case you need it, here's how to use XNAT Central to filter by subject:

First, select the MR Sessions (or PETs) tab from the OASIS3 project page on XNAT Central. Select Options and then Edit Columns, and use the left-right arrows to modify the column list to keep only the MR Session ID and Subject ID on the left side:

![image](https://user-images.githubusercontent.com/264991/45844506-40c6b900-bce8-11e8-8c1e-38d669143b0f.png)

Once you have MR Session ID (or PET session ID) and Subject ID, you can click on the column header for Subject, and click on "Filter":

![image](https://user-images.githubusercontent.com/264991/45844567-7370b180-bce8-11e8-8154-b83b061e69e1.png)

You can use this "Filter" option to include only the subject whose ID you want to download sessions for:

![image](https://user-images.githubusercontent.com/264991/45844608-913e1680-bce8-11e8-9401-d127bc5330e9.png)

Once you have the list filtered by subject, you can use Options -> Edit Columns again to remove the Subject ID from the columns display. Then you can use Options -> Spreadsheet to download a spreadsheet of only the resulting items.

Once you have the MR and/or PET scans downloaded for your subject, you can use this same process to filter and get a spreadsheet for FreeSurfer IDs (from the FreeSurfers tab) or PUP (PET pipeline output) IDs (from the PUPs tab) for specific subjects. You'll just have to reorganize it on your own at the moment if you want one folder per subject.

**Comment by sarahkeefe** [comment]
Oh, for some reason your script output only showed up in my notification email and not in the thread. Sorry if I wasn't clear about using subject names. Subject names won't work in the script as it is currently written. You want to use the column labeled MR ID (MR Session) for MR sessions  (see below): 

![image](https://user-images.githubusercontent.com/264991/45845999-30184200-bcec-11e8-9df6-80a5c7138985.png)

The ID should look like this: OAS30001_MR_d0129. 

for PET, use the column labeled XNAT_PETSESSIONDATA ID (PET). The ID should look like: OAS30001_AV45_d2430.

For FreeSurfer, use the column labeled FS_FSDATA ID (Freesurfer). The ID should look like: OAS30001_Freesurfer53_d0129.

For PUP, use the column labeled PUP_PUPTIMECOURSEDATA ID (PUP). The ID should look like: OAS30001_AV45_PUPTIMECOURSE_d2430.

**Comment by YasmineMH1997** [comment]
Hello I am also trying to download the MR in BIDS format. 
But I keep getting errors: 
$ ./download_oasis_scans_bids.sh MRBIDS.csv "/c/Users/yasmi/Desktop/Oasis/BIDS" Yasmine
Enter your password for accessing OASIS data on XNAT Central:
.ownloading all scans for MR ID
/scans/ALL/files?format=tar.gzarchive/projects/OASIS3/subjects/MR ID
curl: (3) URL using bad/illegal format or missing URL
, or the download failed.an download. Either could not find any scans for MR ID
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/MR': No such file or directory
rm: cannot remove 'ID'$'\r''.tar.gz': No such file or directory
.one with MR ID

.ownloading all scans for OAS30001_MR_d0129
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experime/scans/ALL/files?format=tar.gz
curl: (3) URL using bad/illegal format or missing URL
Could not complete the scan download. Either could not find any scans for OAS300, or the download failed.
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/OAS30001_MR_d0129'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0129

.ownloading all scans for OAS30001_MR_d0757
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experime/scans/ALL/files?format=tar.gz
curl: (3) URL using bad/illegal format or missing URL
Could not complete the scan download. Either could not find any scans for OAS300, or the download failed.
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/OAS30001_MR_d0757'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0757

**Comment by YasmineMH1997** [comment]
**Help please. Nothing is being downloaded**
: /c/Users/yasmi/Desktop/Oasis/BIDS/OAS30017_MR_d0054.tar.gz: Invalid
Warning: argument
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (23) Failure writing output to destination
Could not complete the scan download. Either could not find any scans for OAS30017_MR_d0054, or the download failed.
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/OAS30017_MR_d0054.tar.gz': No such file or directory
Done with OAS30017_MR_d0054.

Downloading all scans for OAS30018_MR_d0070.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30018/experiments/OAS30018_MR_d0070/scans/ALL/files?format=tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file
Warning: /c/Users/yasmi/Desktop/Oasis/BIDS/OAS30018_MR_d0070.tar.gz: Invalid
Warning: argument
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (23) Failure writing output to destination
Could not complete the scan download. Either could not find any scans for OAS30018_MR_d0070, or the download failed.
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/OAS30018_MR_d0070.tar.gz': No such file or directory
Done with OAS30018_MR_d0070.

Downloading all scans for OAS30018_MR_d0893.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30018/experiments/OAS30018_MR_d0893/scans/ALL/files?format=tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to open the file
Warning: /c/Users/yasmi/Desktop/Oasis/BIDS/OAS30018_MR_d0893.tar.gz: Invalid
Warning: argument
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (23) Failure writing output to destination
Could not complete the scan download. Either could not find any scans for OAS30018_MR_d0893, or the download failed.
rm: cannot remove '/c/Users/yasmi/Desktop/Oasis/BIDS/OAS30018_MR_d0893.tar.gz': No such file or directory
Done with OAS30018_MR_d0893.

Downloading all scans for OAS30019_MR_d0376.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30019/experiments/OAS30019_MR_d0376/scans/ALL/files?format=tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

**Comment by DishengLL** [comment]
same issue

**Comment by sarahkeefe** [comment]
Hi, this issue is closed and was resolved for the first user who posted in 2018. If you're running into an error you can go ahead and open a new issue. Please include details on what operating system you are using, the exact command you're running, a screenshot or copy-and-paste text of the output you're getting, and a screenshot or copy of your input CSV file.
