### ISSUE TITLE
Did not find a T1w scan for OAS30290_MR_d0000

### ISSUE THREAD

**Issue by czp19940707** [NrgXnat/oasis-scripts#40]
When I run download_oasis_scans.sh, I encounter this error.

Checking for a T1w scan for OAS30288_MR_d0897.
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30288/experiments/OAS30288_MR_d0897/scans/T1w/files?format=zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
Did not find a T1w scan for OAS30288_MR_d0897.

My command is:
bash download_oasis_scans.sh /media/shucheng/MyBook/2024_OASIS/OASIS3_freesurfer/1.csv /media/shucheng/MyBook/2024_OASIS/OASIS3_freesurfer chenzhenpeng T1w

I have obtained permission to download the data and am able to log in to the website https://www.nitrc.org/projects/oasis3.

I am also unable to download the zip file. 
For example, clicking on this link: https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experiments/OAS30001_MR_d0129/assessors/OAS30001_Freesurfer53_d0129/files?format=zip 
redirects me to 
https://sites.wustl.edu/oasisbrains/central-xnat/.

**Comment by sarahkeefe** [comment]
Hi, apologies, the scripts in this repository were slightly out of date. We recently moved the OASIS data from XNAT Central to NITRC-IR and the script URLs still pointed to XNAT Central. I just pushed a big update to the script repository that should remedy this. Try obtaining an updated copy of the scripts and re-attempt your command and feel free to re-open if you still run into issues.

**Comment by czp19940707** [comment]
Thank you very much for your response. The new version of the script can download successfully. Thank you.
