### ISSUE TITLE
Unable to download from URL

### ISSUE THREAD

**Issue by xinzhao13** [NrgXnat/oasis-scripts#41]
Hi

I have received the approval to download oasis3 data, but have been struggling to download MR scans into bids-structured folders today using `download_oasis_scans_bids.sh` today. I have tested and downloaded from XNAT (https://www.nitrc.org/) using either the desktop client or as zipped file -- all were fine which means my password and username should be correct. Please would you be able to help? Thank you!

The first line below is the command I ran and the rest :

$ sh download_oasis_scans_bids.sh oasis_scan_download_example.csv bids user_name
Enter your password for accessing OASIS data on XNAT Central:
.ownloading all scans for OAS30001_MR_d0129
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experime/scans/ALL/files?format=tar.gz
curl: (3) URL rejected: Malformed input to a URL function
Could not complete the scan download. Either could not find any scans for OAS300, or the download failed.
rm: cannot remove 'bids/OAS30001_MR_d0129'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0129

.ownloading all scans for OAS30001_MR_d0757
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experime/scans/ALL/files?format=tar.gz
curl: (3) URL rejected: Malformed input to a URL function
Could not complete the scan download. Either could not find any scans for OAS300, or the download failed.
rm: cannot remove 'bids/OAS30001_MR_d0757'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d0757

.ownloading all scans for OAS30001_MR_d2430
https://central.xnat.org/data/archive/projects/OASIS3/subjects/OAS30001/experime/scans/ALL/files?format=tar.gz
curl: (3) URL rejected: Malformed input to a URL function
Could not complete the scan download. Either could not find any scans for OAS300, or the download failed.
rm: cannot remove 'bids/OAS30001_MR_d2430'$'\r''.tar.gz': No such file or directory
.one with OAS30001_MR_d2430

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 302 Found
Cache-Control: no-cache
Content-length: 0
Location: https://sites.wustl.edu/oasisbrains/central-xnat/

**Comment by sarahkeefe** [comment]
Hi, two things - 

First, many apologies - the scripts in this repository were slightly out of date. We recently moved the OASIS data from XNAT Central to NITRC-IR and the script URLs still pointed to XNAT Central. I just pushed a big update to the script repository that should remedy this. 

Second, when you see output like
`.ownloading all scans for OAS30001_MR_d0129` (with the dot at the beginning of some lines)
and
`'bids/OAS30001_MR_d0757'$'\r''.tar.gz'` (with the '\r' in the output)
those are indicators that your input CSV file is not in Unix format. See the [Unix formatting section of the README](https://github.com/NrgXnat/oasis-scripts?tab=readme-ov-file#note-on-unix-file-formatting) for details on how to fix this.

Try obtaining an updated copy of the scripts, correcting the formatting of your file, and then re-attempt your command. Thanks!
