### ISSUE TITLE
Can't download OASIS3_AV1451 files

### ISSUE THREAD

**Issue by ngonzalezigc** [NrgXnat/oasis-scripts#42]
Initially I couldn't download PET scans from OASIS3 Tau using the updated scripts due to the change from XNAT to NITRC. I was using the script `download_scans/download_oasis_scans.sh` like such `download_oasis_scans.sh my_file.csv output/directory my_user ALL OASIS3_AV1451`. However, the script didn't take into account that I specified the Tau project id and used OASIS3. After looking for a while in the code I noticed that you use a variable called `EXPERIMENT_LABEL`, which isn't defined before, so I changed it locally to `EXPERIMENT_ID` to fix it. I think this error replicates across other scripts.

**Comment by sarahkeefe** [comment]
Oops! Thank you! Corrected the scan download scripts - let me know if you run into any other issues.
