### ISSUE TITLE
Cannot download Freesurfer or MR Scans (URL using bad / illegal format)

### ISSUE THREAD

**Issue by Nandishounak** [NrgXnat/oasis-scripts#46]
Hello,
I cannot download the FreeSurfer or MR Scan files using the scripts. I am getting the following error-

<img width="768" alt="Screenshot 2024-09-04 at 4 32 25 PM" src="https://github.com/user-attachments/assets/c1a0edd6-3270-4895-a1d2-d5276c26b680">

Could you please help me out in resolving the issue?

Thanks and best,
Shounak

**Comment by sarahkeefe** [comment]
Hi, make sure you follow the instructions in the README on "converting your CSV file to Unix format". This is the error that happens if your file isn't in Unix format Closing this issue since it's covered in the README..

**Comment by Nandishounak** [comment]
Thank you for pointing out the oversight. It works now.
