### ISSUE TITLE
Cannot start session, ID and password should be correct

### ISSUE THREAD

**Issue by atwu** [NrgXnat/oasis-scripts#47]
Dear Sarah,

Hello! I hope you are doing well. I'm trying to download the OASIS3 dataset, but I keep getting the following error: 

```
./download_oasis_scans.sh: line 46: curl: command not found
Error starting session.  Maybe a bad username/password?
```

I double checked that I was granted access to OASIS3 and logged into my account on NITRC-IR, so they should be correct. Could you help me troubleshoot this? Thanks!

EDIT: for reference, I used the following command:
` ./download_oasis_scans.sh *CSV with one column of patient IDs* *empty folder* *my login username*`

**Comment by sarahkeefe** [comment]
Hi, the “curl: command not found” output is indicating that your machine does not have the curl program available. Install curl on your machine and the  make sure you are able to run curl from the same machine you are running the script from, the  retry the download. If you have “wget” installed, you could use the variants of the scripts that use wget instead.

**Comment by atwu** [comment]
Ah, that makes sense. Thank you!
