### ISSUE TITLE
problem downloading

### ISSUE THREAD

**Issue by ET18** [NrgXnat/oasis-scripts#5]
Do I have to have a list of image files' names? Or is it possible to download everything per subject? When I tried with subject names it didn't work (see below). I don't know how to access the image file names. Also if I download them all separately, this would make it difficult to link with other information belonging to that subject.

Enter your password for accessing OASIS data on XNAT Central:
Downloading all scans for OAS30001.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   330  100   330    0     0    806      0 --:--:-- --:--:-- --:--:--   806
Could not download all scans for OAS30001.
Done with OAS30001.
Downloading all scans for OAS30002.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   330  100   330    0     0    884      0 --:--:-- --:--:-- --:--:--   884
Could not download all scans for OAS30002.
Done with OAS30002.
Downloading all scans for OAS30003.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   330  100   330    0     0    691      0 --:--:-- --:--:-- --:--:--   691
Could not download all scans for OAS30003.
Done with OAS30003.

**Comment by ET18** [comment]
Since I couldn't find a way to download per subject, I am now downloading per imaging type, but it is extremely slow. What's the expected the speed?

**Comment by ET18** [comment]
Thank you. 
Is there a faster way to download the data?

**Comment by sarahkeefe** [comment]
Hi, I'm just going to include a link to my replies in the other issue in case future users need information about downloading by subject: [https://github.com/NrgXnat/oasis-scripts/issues/4#issuecomment-423326350](https://github.com/NrgXnat/oasis-scripts/issues/4#issuecomment-423326350). I can work on a separate script to download by subject.

The download speed will vary based on your internet connection. One recent download test I did gave me a download speed of about 15 MB/s but this will probably be different for everyone.

**Comment by ET18** [comment]
my internet speed is 20MB/s but download speed is about 100 times slower than this.

**Comment by sarahkeefe** [comment]
If you're using the download_oasis_scans.sh script you could try using the download_oasis_scans_wget.sh script and see if the version that uses the wget command performs more quickly for you.

**Comment by ET18** [comment]
Hello, I tried wget as well and it seems it is your end that is uploading very slow. Specifically speed is less than 100kb/sec. It is not my download speed because I tested this various ways from various network connections and my speed is more than 100x this speed. Could you please have a look into this? I need this data rather urgently and at this rate it will take weeks to download, I'd appreciate any help with speeding this up.

**Comment by sarahkeefe** [comment]
Hi, I'm sorry, it may be an issue with your network's ability to connect to the XNAT Central website in particular. Or it may be due to other concurrent download traffic slowing down the speed. The XNAT Central team has been working on figuring out connection and speed issues. 

I'm going to close this issue as download speed is not an issue with the script specifically.
