### ISSUE TITLE
download_oasis_scans_tar.sh produce files with improper unix permissions

### ISSUE THREAD

**Issue by gdevenyi** [NrgXnat/oasis-scripts#6]
There is probably an issue with XNAT, but it could be fixed with the script.

Default file permissions after running:
```
----r----- 1 devgab ciclab 11522227 Oct 30  2017 OAS30007_MR_d0061/anat2/sub-OAS30007_ses-d0061_run-01_T1w.nii.gz
```

Read only for group, a very odd choice.

``chmod u=rwX,g=rwX $file`` on each file after download would fix this up for "normal" permissions.

**Comment by gdevenyi** [comment]
I suspect this is XNAT's or the original uploader's fault. tar.gz files preserve their original permissions during packing.

**Comment by sarahkeefe** [comment]
I updated the scripts and I'll let the XNAT team know about it. I'm going to close this issue for now, feel free to reopen or open a new one if you find any more problems.
