### ISSUE TITLE
data not downloading

### ISSUE THREAD

**Issue by philoxy4** [NrgXnat/oasis-scripts#9]
Am a new bee to github use but have spent about 3 days trying to retrieve the PET scan files data without success. I got a bunch of message as below. Can anyone help please?

`E6220@E6220-PC MINGW64 ~/Desktop/oasis-scripts-master
$ ./download_oasis_scans_bids.sh philoxy.csv New_Folder philoxy4
Enter your password for accessing OASIS data on XNAT Central:
.ownloading all scans for ﻿MR ID
/scans/ALL/files?format=tar.gzarchive/projects/OASIS3/subjects/﻿MR ID/experiments/﻿MR ID
curl: (3) URL using bad/illegal format or missing URL
, or the download failed.an download. Either could not find any scans for ﻿MR ID
.one with ﻿MR ID

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Set-Cookie: SESSION_EXPIRATION_TIME="1564456613407,900000"; Version=1; Path=/
Date: Tue, 30 Jul 2019 03:16:53 GMT
Accept-Ranges: bytes
Server: Noelios-Restlet-Engine/1.1.10
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
Content-Security-Policy: frame-ancestors 'self'
Content-Length: 0
`

**Comment by sarahkeefe** [comment]
Hi! 
From a quick look at the error message and output it seems most likely that the conversion to Unix format didn't work correctly. Did you try any of the Unix file conversion methods in this section of the readme? [https://github.com/NrgXnat/oasis-scripts#note-on-unix-file-formatting](https://github.com/NrgXnat/oasis-scripts#note-on-unix-file-formatting)

Additionally, it looks like you are using MINGW on windows - I think if you are using that, you can just type in

`dos2unix your_file_name.csv` 

and press Enter, and that will convert your file to Unix format. Give that a try.

**Comment by sarahkeefe** [comment]
Hello, I haven't heard anything on this issue in a while so I'm going to close it - let me know if you still experience any downloading problems with this error message.
